/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
**                   Auther: brinkqiang                            **
********************************************************************/
// source: luaipdb.pkg

#ifndef __LUAIPDB_SOL_H__
#define __LUAIPDB_SOL_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"

LUA_API int luaopen_luaipdb(lua_State* L);
LUA_API int require_luaipdb(lua_State* L);

#ifdef __cplusplus
}
#endif

#endif  // __LUAIPDB_SOL_H__
